### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by fabiomeneses** [m242/maildrop#9]
Anyone can help me run MailDrop for the first time? Im getting errors wieh i try to set up the web server. 
This is what i get...

root@prd1:/segundoemail/maildrop/web/target/universal/web-2.0/bin# sudo ./web
Play server process ID is 15898
14:29:57,669 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
14:29:57,669 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:29:57,669 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/segundoemail/maildrop/web/target/universal/web-2.0/lib/default.common-2.0.jar!/logback.xml]
14:29:57,670 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs multiple times on the classpath.
14:29:57,670 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/segundoemail/maildrop/web/target/universal/web-2.0/lib/com.typesafe.play.play_2.10-2.3.4.jar!/logback.xml]
14:29:57,670 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback.xml] occurs at [jar:file:/segundoemail/maildrop/web/target/universal/web-2.0/lib/default.common-2.0.jar!/logback.xml]
14:29:57,692 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@2296a71f - URL [jar:file:/segundoemail/maildrop/web/target/universal/web-2.0/lib/default.common-2.0.jar!/logback.xml] is not of type file
14:29:57,881 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
14:29:57,882 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
14:29:57,891 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
14:29:57,922 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
14:29:57,990 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.heluna.maildrop.smtp.filters.SPFLogger] to ERROR
14:29:57,990 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
14:29:57,990 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
14:29:57,991 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
14:29:57,992 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@50b5f5f6 - Registering current configuration as safe fallback point

[info] play - Application started (Prod)
Oops, cannot start the server.
org.jboss.netty.channel.ChannelException: Failed to bind to: /0.0.0.0:9000
        at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:129)
        at play.core.server.NettyServer$$anonfun$8.apply(NettyServer.scala:126)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer.<init>(NettyServer.scala:126)
        at play.core.server.NettyServer$.createServer(NettyServer.scala:243)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:280)
        at play.core.server.NettyServer$$anonfun$main$3.apply(NettyServer.scala:275)
        at scala.Option.map(Option.scala:145)
        at play.core.server.NettyServer$.main(NettyServer.scala:275)
        at play.core.server.NettyServer.main(NettyServer.scala)
Caused by: java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:174)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:139)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:77)
        at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:372)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:296)
        at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:701)

Anyone can help me? 
Really appreciate....

**Comment by m242** [comment]
Ths sound like you have something listening on port 9000. You can add a line "http.port=8080" (or whichever port you like) in application.conf.
